// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: protos/tuner.proto

package tuner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EPDInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EPDInfoRequest) Reset() {
	*x = EPDInfoRequest{}
	mi := &file_protos_tuner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EPDInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EPDInfoRequest) ProtoMessage() {}

func (x *EPDInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_tuner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EPDInfoRequest.ProtoReflect.Descriptor instead.
func (*EPDInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_tuner_proto_rawDescGZIP(), []int{0}
}

type EPDInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EPDInfo) Reset() {
	*x = EPDInfo{}
	mi := &file_protos_tuner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EPDInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EPDInfo) ProtoMessage() {}

func (x *EPDInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_tuner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EPDInfo.ProtoReflect.Descriptor instead.
func (*EPDInfo) Descriptor() ([]byte, []int) {
	return file_protos_tuner_proto_rawDescGZIP(), []int{1}
}

func (x *EPDInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EPDInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_protos_tuner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_tuner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_protos_tuner_proto_rawDescGZIP(), []int{2}
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUuid       string                 `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	Epoch         int32                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Start         int32                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Coefficients  []float64              `protobuf:"fixed64,6,rep,packed,name=coefficients,proto3" json:"coefficients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_protos_tuner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_tuner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_protos_tuner_proto_rawDescGZIP(), []int{3}
}

func (x *JobResponse) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

func (x *JobResponse) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *JobResponse) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *JobResponse) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *JobResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *JobResponse) GetCoefficients() []float64 {
	if x != nil {
		return x.Coefficients
	}
	return nil
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUuid       string                 `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Gradients     []float64              `protobuf:"fixed64,3,rep,packed,name=gradients,proto3" json:"gradients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_protos_tuner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_tuner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_protos_tuner_proto_rawDescGZIP(), []int{4}
}

func (x *ResultRequest) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

func (x *ResultRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ResultRequest) GetGradients() []float64 {
	if x != nil {
		return x.Gradients
	}
	return nil
}

type ResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAck) Reset() {
	*x = ResultAck{}
	mi := &file_protos_tuner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAck) ProtoMessage() {}

func (x *ResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_tuner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAck.ProtoReflect.Descriptor instead.
func (*ResultAck) Descriptor() ([]byte, []int) {
	return file_protos_tuner_proto_rawDescGZIP(), []int{5}
}

var File_protos_tuner_proto protoreflect.FileDescriptor

const file_protos_tuner_proto_rawDesc = "" +
	"\n" +
	"\x12protos/tuner.proto\x12\x05tuner\"\x10\n" +
	"\x0eEPDInfoRequest\"A\n" +
	"\aEPDInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\"\f\n" +
	"\n" +
	"JobRequest\"\xa6\x01\n" +
	"\vJobResponse\x12\x19\n" +
	"\bjob_uuid\x18\x01 \x01(\tR\ajobUuid\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x05R\x05epoch\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x05R\x03end\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\"\n" +
	"\fcoefficients\x18\x06 \x03(\x01R\fcoefficients\"d\n" +
	"\rResultRequest\x12\x19\n" +
	"\bjob_uuid\x18\x01 \x01(\tR\ajobUuid\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1c\n" +
	"\tgradients\x18\x03 \x03(\x01R\tgradients\"\v\n" +
	"\tResultAck2\xaf\x01\n" +
	"\x05Tuner\x127\n" +
	"\x0eRequestEPDInfo\x12\x15.tuner.EPDInfoRequest\x1a\x0e.tuner.EPDInfo\x123\n" +
	"\n" +
	"RequestJob\x12\x11.tuner.JobRequest\x1a\x12.tuner.JobResponse\x128\n" +
	"\x0eRegisterResult\x12\x14.tuner.ResultRequest\x1a\x10.tuner.ResultAckB\x14Z\x12./grpc/tuner;tunerb\x06proto3"

var (
	file_protos_tuner_proto_rawDescOnce sync.Once
	file_protos_tuner_proto_rawDescData []byte
)

func file_protos_tuner_proto_rawDescGZIP() []byte {
	file_protos_tuner_proto_rawDescOnce.Do(func() {
		file_protos_tuner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_tuner_proto_rawDesc), len(file_protos_tuner_proto_rawDesc)))
	})
	return file_protos_tuner_proto_rawDescData
}

var file_protos_tuner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_tuner_proto_goTypes = []any{
	(*EPDInfoRequest)(nil), // 0: tuner.EPDInfoRequest
	(*EPDInfo)(nil),        // 1: tuner.EPDInfo
	(*JobRequest)(nil),     // 2: tuner.JobRequest
	(*JobResponse)(nil),    // 3: tuner.JobResponse
	(*ResultRequest)(nil),  // 4: tuner.ResultRequest
	(*ResultAck)(nil),      // 5: tuner.ResultAck
}
var file_protos_tuner_proto_depIdxs = []int32{
	0, // 0: tuner.Tuner.RequestEPDInfo:input_type -> tuner.EPDInfoRequest
	2, // 1: tuner.Tuner.RequestJob:input_type -> tuner.JobRequest
	4, // 2: tuner.Tuner.RegisterResult:input_type -> tuner.ResultRequest
	1, // 3: tuner.Tuner.RequestEPDInfo:output_type -> tuner.EPDInfo
	3, // 4: tuner.Tuner.RequestJob:output_type -> tuner.JobResponse
	5, // 5: tuner.Tuner.RegisterResult:output_type -> tuner.ResultAck
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_tuner_proto_init() }
func file_protos_tuner_proto_init() {
	if File_protos_tuner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_tuner_proto_rawDesc), len(file_protos_tuner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_tuner_proto_goTypes,
		DependencyIndexes: file_protos_tuner_proto_depIdxs,
		MessageInfos:      file_protos_tuner_proto_msgTypes,
	}.Build()
	File_protos_tuner_proto = out.File
	file_protos_tuner_proto_goTypes = nil
	file_protos_tuner_proto_depIdxs = nil
}
