// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package uci

import (
	"github.com/paulsonkoly/chess-3/board"
	"github.com/paulsonkoly/chess-3/chess"
	"github.com/paulsonkoly/chess-3/move"
	"github.com/paulsonkoly/chess-3/search"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSearch creates a new instance of MockSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearch {
	mock := &MockSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearch is an autogenerated mock type for the Search type
type MockSearch struct {
	mock.Mock
}

type MockSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearch) EXPECT() *MockSearch_Expecter {
	return &MockSearch_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockSearch
func (_mock *MockSearch) Clear() {
	_mock.Called()
	return
}

// MockSearch_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockSearch_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockSearch_Expecter) Clear() *MockSearch_Clear_Call {
	return &MockSearch_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockSearch_Clear_Call) Run(run func()) *MockSearch_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSearch_Clear_Call) Return() *MockSearch_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSearch_Clear_Call) RunAndReturn(run func()) *MockSearch_Clear_Call {
	_c.Run(run)
	return _c
}

// Go provides a mock function for the type MockSearch
func (_mock *MockSearch) Go(board1 *board.Board, vs ...search.Option) (chess.Score, move.Move) {
	var tmpRet mock.Arguments
	if len(vs) > 0 {
		tmpRet = _mock.Called(board1, vs)
	} else {
		tmpRet = _mock.Called(board1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Go")
	}

	var r0 chess.Score
	var r1 move.Move
	if returnFunc, ok := ret.Get(0).(func(*board.Board, ...search.Option) (chess.Score, move.Move)); ok {
		return returnFunc(board1, vs...)
	}
	if returnFunc, ok := ret.Get(0).(func(*board.Board, ...search.Option) chess.Score); ok {
		r0 = returnFunc(board1, vs...)
	} else {
		r0 = ret.Get(0).(chess.Score)
	}
	if returnFunc, ok := ret.Get(1).(func(*board.Board, ...search.Option) move.Move); ok {
		r1 = returnFunc(board1, vs...)
	} else {
		r1 = ret.Get(1).(move.Move)
	}
	return r0, r1
}

// MockSearch_Go_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Go'
type MockSearch_Go_Call struct {
	*mock.Call
}

// Go is a helper method to define mock.On call
//   - board1 *board.Board
//   - vs ...search.Option
func (_e *MockSearch_Expecter) Go(board1 interface{}, vs ...interface{}) *MockSearch_Go_Call {
	return &MockSearch_Go_Call{Call: _e.mock.On("Go",
		append([]interface{}{board1}, vs...)...)}
}

func (_c *MockSearch_Go_Call) Run(run func(board1 *board.Board, vs ...search.Option)) *MockSearch_Go_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *board.Board
		if args[0] != nil {
			arg0 = args[0].(*board.Board)
		}
		var arg1 []search.Option
		var variadicArgs []search.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]search.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSearch_Go_Call) Return(score chess.Score, move1 move.Move) *MockSearch_Go_Call {
	_c.Call.Return(score, move1)
	return _c
}

func (_c *MockSearch_Go_Call) RunAndReturn(run func(board1 *board.Board, vs ...search.Option) (chess.Score, move.Move)) *MockSearch_Go_Call {
	_c.Call.Return(run)
	return _c
}

// ResizeTT provides a mock function for the type MockSearch
func (_mock *MockSearch) ResizeTT(n int) {
	_mock.Called(n)
	return
}

// MockSearch_ResizeTT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeTT'
type MockSearch_ResizeTT_Call struct {
	*mock.Call
}

// ResizeTT is a helper method to define mock.On call
//   - n int
func (_e *MockSearch_Expecter) ResizeTT(n interface{}) *MockSearch_ResizeTT_Call {
	return &MockSearch_ResizeTT_Call{Call: _e.mock.On("ResizeTT", n)}
}

func (_c *MockSearch_ResizeTT_Call) Run(run func(n int)) *MockSearch_ResizeTT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSearch_ResizeTT_Call) Return() *MockSearch_ResizeTT_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSearch_ResizeTT_Call) RunAndReturn(run func(n int)) *MockSearch_ResizeTT_Call {
	_c.Run(run)
	return _c
}
