// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: protos/datagen.proto

package datagen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Datagen_RequestConfig_FullMethodName  = "/datagen.Datagen/RequestConfig"
	Datagen_RequestOpening_FullMethodName = "/datagen.Datagen/RequestOpening"
	Datagen_RegisterGame_FullMethodName   = "/datagen.Datagen/RegisterGame"
)

// DatagenClient is the client API for Datagen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatagenClient interface {
	RequestConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Config, error)
	RequestOpening(ctx context.Context, in *OpeningRequest, opts ...grpc.CallOption) (*Opening, error)
	RegisterGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*GameAck, error)
}

type datagenClient struct {
	cc grpc.ClientConnInterface
}

func NewDatagenClient(cc grpc.ClientConnInterface) DatagenClient {
	return &datagenClient{cc}
}

func (c *datagenClient) RequestConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Config)
	err := c.cc.Invoke(ctx, Datagen_RequestConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datagenClient) RequestOpening(ctx context.Context, in *OpeningRequest, opts ...grpc.CallOption) (*Opening, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Opening)
	err := c.cc.Invoke(ctx, Datagen_RequestOpening_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datagenClient) RegisterGame(ctx context.Context, in *Game, opts ...grpc.CallOption) (*GameAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameAck)
	err := c.cc.Invoke(ctx, Datagen_RegisterGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatagenServer is the server API for Datagen service.
// All implementations must embed UnimplementedDatagenServer
// for forward compatibility.
type DatagenServer interface {
	RequestConfig(context.Context, *ConfigRequest) (*Config, error)
	RequestOpening(context.Context, *OpeningRequest) (*Opening, error)
	RegisterGame(context.Context, *Game) (*GameAck, error)
	mustEmbedUnimplementedDatagenServer()
}

// UnimplementedDatagenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatagenServer struct{}

func (UnimplementedDatagenServer) RequestConfig(context.Context, *ConfigRequest) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestConfig not implemented")
}
func (UnimplementedDatagenServer) RequestOpening(context.Context, *OpeningRequest) (*Opening, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestOpening not implemented")
}
func (UnimplementedDatagenServer) RegisterGame(context.Context, *Game) (*GameAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGame not implemented")
}
func (UnimplementedDatagenServer) mustEmbedUnimplementedDatagenServer() {}
func (UnimplementedDatagenServer) testEmbeddedByValue()                 {}

// UnsafeDatagenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatagenServer will
// result in compilation errors.
type UnsafeDatagenServer interface {
	mustEmbedUnimplementedDatagenServer()
}

func RegisterDatagenServer(s grpc.ServiceRegistrar, srv DatagenServer) {
	// If the following call pancis, it indicates UnimplementedDatagenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Datagen_ServiceDesc, srv)
}

func _Datagen_RequestConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatagenServer).RequestConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datagen_RequestConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatagenServer).RequestConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datagen_RequestOpening_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpeningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatagenServer).RequestOpening(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datagen_RequestOpening_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatagenServer).RequestOpening(ctx, req.(*OpeningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datagen_RegisterGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Game)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatagenServer).RegisterGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datagen_RegisterGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatagenServer).RegisterGame(ctx, req.(*Game))
	}
	return interceptor(ctx, in, info, handler)
}

// Datagen_ServiceDesc is the grpc.ServiceDesc for Datagen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Datagen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datagen.Datagen",
	HandlerType: (*DatagenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestConfig",
			Handler:    _Datagen_RequestConfig_Handler,
		},
		{
			MethodName: "RequestOpening",
			Handler:    _Datagen_RequestOpening_Handler,
		},
		{
			MethodName: "RegisterGame",
			Handler:    _Datagen_RegisterGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/datagen.proto",
}
