// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/datagen.proto

package datagen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_protos_datagen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_datagen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_protos_datagen_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftNodes     int64                  `protobuf:"varint,1,opt,name=soft_nodes,json=softNodes,proto3" json:"soft_nodes,omitempty"`
	HardNodes     int64                  `protobuf:"varint,2,opt,name=hard_nodes,json=hardNodes,proto3" json:"hard_nodes,omitempty"`
	Draw          bool                   `protobuf:"varint,3,opt,name=draw,proto3" json:"draw,omitempty"`
	DrawAfter     int32                  `protobuf:"varint,4,opt,name=draw_after,json=drawAfter,proto3" json:"draw_after,omitempty"`
	DrawMargin    int32                  `protobuf:"varint,5,opt,name=draw_margin,json=drawMargin,proto3" json:"draw_margin,omitempty"`
	DrawCount     int32                  `protobuf:"varint,6,opt,name=draw_count,json=drawCount,proto3" json:"draw_count,omitempty"`
	Win           bool                   `protobuf:"varint,7,opt,name=win,proto3" json:"win,omitempty"`
	WinAfter      int32                  `protobuf:"varint,8,opt,name=win_after,json=winAfter,proto3" json:"win_after,omitempty"`
	WinMargin     int32                  `protobuf:"varint,9,opt,name=win_margin,json=winMargin,proto3" json:"win_margin,omitempty"`
	WinCount      int32                  `protobuf:"varint,10,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_protos_datagen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_protos_datagen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_protos_datagen_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetSoftNodes() int64 {
	if x != nil {
		return x.SoftNodes
	}
	return 0
}

func (x *Config) GetHardNodes() int64 {
	if x != nil {
		return x.HardNodes
	}
	return 0
}

func (x *Config) GetDraw() bool {
	if x != nil {
		return x.Draw
	}
	return false
}

func (x *Config) GetDrawAfter() int32 {
	if x != nil {
		return x.DrawAfter
	}
	return 0
}

func (x *Config) GetDrawMargin() int32 {
	if x != nil {
		return x.DrawMargin
	}
	return 0
}

func (x *Config) GetDrawCount() int32 {
	if x != nil {
		return x.DrawCount
	}
	return 0
}

func (x *Config) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *Config) GetWinAfter() int32 {
	if x != nil {
		return x.WinAfter
	}
	return 0
}

func (x *Config) GetWinMargin() int32 {
	if x != nil {
		return x.WinMargin
	}
	return 0
}

func (x *Config) GetWinCount() int32 {
	if x != nil {
		return x.WinCount
	}
	return 0
}

type OpeningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningRequest) Reset() {
	*x = OpeningRequest{}
	mi := &file_protos_datagen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningRequest) ProtoMessage() {}

func (x *OpeningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_datagen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningRequest.ProtoReflect.Descriptor instead.
func (*OpeningRequest) Descriptor() ([]byte, []int) {
	return file_protos_datagen_proto_rawDescGZIP(), []int{2}
}

type Opening struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opening) Reset() {
	*x = Opening{}
	mi := &file_protos_datagen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opening) ProtoMessage() {}

func (x *Opening) ProtoReflect() protoreflect.Message {
	mi := &file_protos_datagen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opening.ProtoReflect.Descriptor instead.
func (*Opening) Descriptor() ([]byte, []int) {
	return file_protos_datagen_proto_rawDescGZIP(), []int{3}
}

func (x *Opening) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wdl           int32                  `protobuf:"varint,1,opt,name=wdl,proto3" json:"wdl,omitempty"`
	Positions     []*Position            `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_protos_datagen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_protos_datagen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_protos_datagen_proto_rawDescGZIP(), []int{4}
}

func (x *Game) GetWdl() int32 {
	if x != nil {
		return x.Wdl
	}
	return 0
}

func (x *Game) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`
	BestMove      int32                  `protobuf:"varint,2,opt,name=best_move,json=bestMove,proto3" json:"best_move,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_protos_datagen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_protos_datagen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_protos_datagen_proto_rawDescGZIP(), []int{5}
}

func (x *Position) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *Position) GetBestMove() int32 {
	if x != nil {
		return x.BestMove
	}
	return 0
}

func (x *Position) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GameAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAck) Reset() {
	*x = GameAck{}
	mi := &file_protos_datagen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAck) ProtoMessage() {}

func (x *GameAck) ProtoReflect() protoreflect.Message {
	mi := &file_protos_datagen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAck.ProtoReflect.Descriptor instead.
func (*GameAck) Descriptor() ([]byte, []int) {
	return file_protos_datagen_proto_rawDescGZIP(), []int{6}
}

var File_protos_datagen_proto protoreflect.FileDescriptor

const file_protos_datagen_proto_rawDesc = "" +
	"\n" +
	"\x14protos/datagen.proto\x12\adatagen\"\x0f\n" +
	"\rConfigRequest\"\xa4\x02\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"soft_nodes\x18\x01 \x01(\x03R\tsoftNodes\x12\x1d\n" +
	"\n" +
	"hard_nodes\x18\x02 \x01(\x03R\thardNodes\x12\x12\n" +
	"\x04draw\x18\x03 \x01(\bR\x04draw\x12\x1d\n" +
	"\n" +
	"draw_after\x18\x04 \x01(\x05R\tdrawAfter\x12\x1f\n" +
	"\vdraw_margin\x18\x05 \x01(\x05R\n" +
	"drawMargin\x12\x1d\n" +
	"\n" +
	"draw_count\x18\x06 \x01(\x05R\tdrawCount\x12\x10\n" +
	"\x03win\x18\a \x01(\bR\x03win\x12\x1b\n" +
	"\twin_after\x18\b \x01(\x05R\bwinAfter\x12\x1d\n" +
	"\n" +
	"win_margin\x18\t \x01(\x05R\twinMargin\x12\x1b\n" +
	"\twin_count\x18\n" +
	" \x01(\x05R\bwinCount\"\x10\n" +
	"\x0eOpeningRequest\"\x1b\n" +
	"\aOpening\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\"I\n" +
	"\x04Game\x12\x10\n" +
	"\x03wdl\x18\x01 \x01(\x05R\x03wdl\x12/\n" +
	"\tpositions\x18\x02 \x03(\v2\x11.datagen.PositionR\tpositions\"O\n" +
	"\bPosition\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\x12\x1b\n" +
	"\tbest_move\x18\x02 \x01(\x05R\bbestMove\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"\t\n" +
	"\aGameAck2\xb1\x01\n" +
	"\aDatagen\x128\n" +
	"\rRequestConfig\x12\x16.datagen.ConfigRequest\x1a\x0f.datagen.Config\x12;\n" +
	"\x0eRequestOpening\x12\x17.datagen.OpeningRequest\x1a\x10.datagen.Opening\x12/\n" +
	"\fRegisterGame\x12\r.datagen.Game\x1a\x10.datagen.GameAckB\x18Z\x16./grpc/datagen;datagenb\x06proto3"

var (
	file_protos_datagen_proto_rawDescOnce sync.Once
	file_protos_datagen_proto_rawDescData []byte
)

func file_protos_datagen_proto_rawDescGZIP() []byte {
	file_protos_datagen_proto_rawDescOnce.Do(func() {
		file_protos_datagen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_datagen_proto_rawDesc), len(file_protos_datagen_proto_rawDesc)))
	})
	return file_protos_datagen_proto_rawDescData
}

var file_protos_datagen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_datagen_proto_goTypes = []any{
	(*ConfigRequest)(nil),  // 0: datagen.ConfigRequest
	(*Config)(nil),         // 1: datagen.Config
	(*OpeningRequest)(nil), // 2: datagen.OpeningRequest
	(*Opening)(nil),        // 3: datagen.Opening
	(*Game)(nil),           // 4: datagen.Game
	(*Position)(nil),       // 5: datagen.Position
	(*GameAck)(nil),        // 6: datagen.GameAck
}
var file_protos_datagen_proto_depIdxs = []int32{
	5, // 0: datagen.Game.positions:type_name -> datagen.Position
	0, // 1: datagen.Datagen.RequestConfig:input_type -> datagen.ConfigRequest
	2, // 2: datagen.Datagen.RequestOpening:input_type -> datagen.OpeningRequest
	4, // 3: datagen.Datagen.RegisterGame:input_type -> datagen.Game
	1, // 4: datagen.Datagen.RequestConfig:output_type -> datagen.Config
	3, // 5: datagen.Datagen.RequestOpening:output_type -> datagen.Opening
	6, // 6: datagen.Datagen.RegisterGame:output_type -> datagen.GameAck
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_datagen_proto_init() }
func file_protos_datagen_proto_init() {
	if File_protos_datagen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_datagen_proto_rawDesc), len(file_protos_datagen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_datagen_proto_goTypes,
		DependencyIndexes: file_protos_datagen_proto_depIdxs,
		MessageInfos:      file_protos_datagen_proto_msgTypes,
	}.Build()
	File_protos_datagen_proto = out.File
	file_protos_datagen_proto_goTypes = nil
	file_protos_datagen_proto_depIdxs = nil
}
