name: 'Commit Message Check'

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR branch
        uses: actions/checkout@v4
        with:
          # Checkout using the actual branch name instead of the SHA
          ref: ${{ github.head_ref }}

      - name: Verify branch context
        run: |
          echo "Currently on branch: $(git branch --show-current)"
          git status

      - name: Run commit message check
        run: .github/scripts/checkmessage.sh

