name: 'Commit Message Check'

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR commit safely
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run commit message check
        run: .github/scripts/checkmessage.sh
